# Generated by Django 4.0 on 2022-01-06 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_motto', models.CharField(max_length=255)),
                ('school_logo', models.ImageField(upload_to='logos/')),
                ('school_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('school_address', models.TextField()),
                ('school_website', models.CharField(max_length=50)),
                ('school_type', models.CharField(choices=[('University', 'University'), ('Polythecnic', 'Polythecnic'), ('College', 'College'), ('Academy', 'Academy'), ('Institute', 'Institute'), ('Senior Secondary', 'Senior Secondary'), ('Junior Secondary', 'Junior Secondary'), ('Primary', 'Primary'), ('Nursery', 'Nursery')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('address', models.TextField()),
                ('lga', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('role', models.CharField(max_length=255)),
                ('class_of', models.DateField()),
                ('quote', models.TextField()),
                ('best_friend', models.CharField(max_length=255)),
                ('best_moment', models.TextField()),
                ('phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be          entered in the format: '+234 ...'", regex='^\\+?1?\\d{9,15}$')])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
