# Generated by Django 4.0 on 2022-01-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_motto', models.CharField(max_length=255)),
                ('school_logo', models.ImageField(upload_to='')),
                ('school_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('school_address', models.TextField()),
                ('school_website', models.CharField(max_length=50)),
                ('school_type', models.CharField(choices=[('University', 'University'), ('Polythecnic', 'Polythecnic'), ('College', 'College'), ('Academy', 'Academy'), ('Institute', 'Institute'), ('Senior Secondary', 'Senior Secondary'), ('Junior Secondary', 'Junior Secondary'), ('Primary', 'Primary'), ('Nursery', 'Nursery')], max_length=255)),
            ],
        ),
    ]
