# Generated by Django 4.0 on 2022-01-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
